### PR TITLE
Make async integration more flexible

### PR DESCRIPTION
**Pull request by parzivail**
* Allow custom executor to be specified for mesh building
* Return async task from `scheduleRebuild` that can be joined with at the call source

### CODE REVIEW

**Comment by gliscowo** [comment]
While this generally looks good, I'm not so sure whether simply returning a completed future directly when calling `scheduleRebuild` during building makes sense. If the point of this is to allow the caller to either join the task or get a callback when building is completed, this would be highly misleading.

I'm not entirely sure what the superior approach would be since we could either 
 - cache the future and transparently return it
 - somehow (potentially by returning `null`) signal to the caller that they did not in fact invoke a build process

The first approach feels like it would more generally satisfy the requirement which this PR is trying to cater to, but let me know what you think

**Comment by parzivail** [comment]
~~Well, I figured since the original parameterless overload didn't return the future, the API surface didn't need to change. Either way you mentioned would work, you could even just return the future in the same way that the new overload does, and existing calls would be unaffected.~~

**Comment by parzivail** [comment]
Oh, I misread your comment. I'm not sure what the difference would be returning what's currently returned vs your suggestions, in my testing I found that joining or waiting for the task worked as expected. Both of your assumptions about the point of this feature are correct though, so whichever way you think would be easiest to integrate would be fine.

**Comment by gliscowo** [comment]
I'll incorporate this improvement along with a few other things in a refactor I'm currently doing, thanks for brining it up. As such, I'll close this PR as it won't be necessary anymore
Cheers

**Pull request closed without merging**
