### PR TITLE
extract BlockRenderViewMesh superclass from WorldMesh

### PR DESCRIPTION
**Pull request by parzivail**
* Allows rendering of things that aren't quite a world but can implement a `BlockRenderView`
* `BlockRenderView` gains a new method to allow a subclass to provide a list of entities to render, which returns an empty list by default
* Renames `WorldMesh` to `BlockRenderViewMesh` and replaces the first constructor parameter with a `BlockRenderView` instead of a `World`
* A new derived subclass `WorldMesh` with the first constructor parameter as a `World` should make this a drop-in change without needing to update dependents

One odd thing I noticed was that the entities are pulled from `client.world` instead of the world passed into the constructor. I don't know if that was intentional (I also don't know the side-effects of it) but I emulated that behavior in the new `WorldMesh` subclass regardless.

### CODE REVIEW

**Review by gliscowo — CHANGES_REQUESTED** [review]
I generally approve the overall concept this PR is chasing, although I'm not the largest fan of this specific implementation. 

I'd much prefer if `WorldMesh` was kept as a single class, with a single builder. This builder could then accept either a `World` or a `BlockRenderView` and, depending on which overload was used, pass some method reference or other way of querying entities to the created `WorldMesh`. This keeps the API surface significantly cleaner and still allows the same flexibility

**Comment by parzivail** [comment]
Got it, I'll give it a shot. As for the entity source, should it stay the client world, or should it use the world provided as a parameter? Typically they'd be the same, but I can imagine some opposing use cases.

**Comment by gliscowo** [comment]
Yes, the entity source should be the world provided to the builder - the fact it was using the client world before is an oversight

**Comment by parzivail** [comment]
Alright, after making those changes I now understand that I originally misinterpreted how the API worked -- this should be a lot more succinct.

**Review by gliscowo — APPROVED** [review]

**Comment by gliscowo** [comment]
Thanks for making the changes so quickly, I'm quite happy with this new implementation. If you have no further remarks, I'll go ahead and merge the PR
Cheers

**Comment by parzivail** [comment]
LGTM, cheers

**Pull request merged**
